// Writes ui/src/gen/design.ts from the design system (design/system/tokens.json + glyphs/*.svg), so the canvas never
// hand-copies a label, headline, chart constant or glyph shape. Deterministic; `--check` fails if the file is stale.
//   node ui/scripts/gen.mjs [--check]
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const UI = dirname(dirname(fileURLToPath(import.meta.url)));
const DS = join(UI, "..", "design", "system");
const OUT = join(UI, "src", "gen", "design.ts");

const t = JSON.parse(readFileSync(join(DS, "tokens.json"), "utf8"));

const STATE_KEYS = ["insufficient", "none", "unclear", "you", "agent", "stale"];
const states = {};
for (const k of STATE_KEYS) {
  const s = t.states[k];
  states[k] = { label: s.label, headline: s.headline, legend: s.legend, voiceOver: s.voiceOver, textGlyph: s.textGlyph, ascii: s.ascii };
}
const cal = t.states.calibrationPending;

/** Parses one hand-written template glyph (rects and paths only) into shape records drawn in currentColor. */
function glyph(file) {
  const svg = readFileSync(join(DS, "glyphs", file), "utf8");
  const size = Number(/viewBox="0 0 (\d+) \d+"/.exec(svg)[1]);
  const shapes = [];
  for (const m of svg.matchAll(/<(rect|path)\b([^>]*?)\/>/g)) {
    const a = {};
    for (const am of m[2].matchAll(/([a-z-]+)="([^"]*)"/g)) a[am[1]] = am[2] === "#000" ? "currentColor" : am[2];
    shapes.push({ t: m[1], a });
  }
  if (!shapes.length) throw new Error(`no shapes in ${file}`);
  return { size, shapes };
}
const glyphs = {};
for (const k of STATE_KEYS) for (const px of [16, 18]) glyphs[`${k}-${px}`] = glyph(`state-${k}-${px}.svg`);
for (const px of [16, 18]) glyphs[`mark-${px}`] = glyph(`mark-${px}.svg`);
// the app's own document states (tokens.json appStates): keyed "app:<state>-<px>", drawn from glyphs/app-*-16|18.svg
const APP_KEYS = t.appStates.order;
for (const k of APP_KEYS) for (const px of [16, 18]) glyphs[`app:${k}-${px}`] = glyph(t.appStates[k].files[px].replace(/^glyphs\//, ""));
const appStates = Object.fromEntries(APP_KEYS.map((k) => [k, { label: t.appStates[k].label, legend: t.appStates[k].legend }]));

const copy = {
  disclaimer: t.copy.disclaimer,
  privacyLine: t.copy.privacyLine,
  privacyShort: t.copy.privacyShort,
  tagline: t.copy.tagline,
  question: t.copy.question,
};
// The canvas's own words (tokens.json copy.canvas, UX-V2 §11.1): every sentence and label pages.ts shows that is not an
// engine string. "$about" keys are documentation, not copy.
const stripAbout = (o) => (o && typeof o === "object" && !Array.isArray(o)
  ? Object.fromEntries(Object.entries(o).filter(([k]) => k !== "$about").map(([k, v]) => [k, stripAbout(v)])) : o);
const canvasCopy = stripAbout(t.copy.canvas);
if (!canvasCopy || typeof canvasCopy !== "object") throw new Error("tokens.json copy.canvas missing");

const chart = {
  strip: {
    tickHeight: t.chart.strip.tickHeight, tickGap: t.chart.strip.tickGap, denseAbove: t.chart.strip.denseAbove,
    denseTickHeight: t.chart.strip.denseTickHeight, denseTickGap: t.chart.strip.denseTickGap,
    columnWidth: t.chart.strip.columnWidth, lowNThreshold: t.chart.strip.lowNThreshold,
  },
  ratio: { domain: t.chart.ratio.domain, ticks: t.chart.ratio.ticks },
  badge: { you: t.size.badgeYou, agent: t.size.badgeAgent, radius: t.radius.badge },
};

const body = `// GENERATED by ui/scripts/gen.mjs from design/system/tokens.json and design/system/glyphs/*.svg. Do not edit by hand.

export interface GlyphShape { t: "rect" | "path"; a: { [name: string]: string } }
export interface Glyph { size: number; shapes: GlyphShape[] }

export const STATES = ${JSON.stringify(states, null, 2)} as const;

export const CALIBRATION_PENDING = ${JSON.stringify({ label: cal.label, headline: cal.headline })} as const;

export const APP_STATES = ${JSON.stringify(appStates, null, 2)} as const;

export const COPY = ${JSON.stringify(copy, null, 2)} as const;

export const CHART = ${JSON.stringify(chart, null, 2)} as const;

export const CANVAS_COPY = ${JSON.stringify(canvasCopy, null, 2)} as const;

export const GLYPHS: { [key: string]: Glyph } = ${JSON.stringify(glyphs)};
`;

if (process.argv.includes("--check")) {
  const cur = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (cur !== body) { console.error("ui/src/gen/design.ts is stale: run node ui/scripts/gen.mjs"); process.exit(1); }
  console.log("ui/src/gen/design.ts is current");
} else {
  writeFileSync(OUT, body);
}
