#!/usr/bin/env node
// Copies the design system's shipped files into the engine, which cannot import across its rootDir and ships only
// dist/src (the same reason engine/src/words/tokens.ts is a copy). Run after design/system is regenerated:
//
//   node engine/scripts/sync-design.mjs           rewrite the three copies
//   node engine/scripts/sync-design.mjs --check   fail if a copy differs from its source
//
//   design/system/generated/tokens.ts       -> engine/src/cli/design-tokens.ts   (byte for byte)
//   design/system/generated/tokens.inline.css -> engine/src/output/inline-css.ts (one string constant)
//   design/system/demo-data.v3.json         -> engine/src/demo/data.ts           (one JSON string constant)
//
// engine/test/output/design-sync.test.ts holds each copy to its source (and the CSS to the sha256 recorded by
// design/system/gen/csp-check.mjs), so a design change fails the engine tests until this script has been run.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const check = process.argv.includes("--check");

const tokensTs = readFileSync(join(ROOT, "design/system/generated/tokens.ts"), "utf8");
const css = readFileSync(join(ROOT, "design/system/generated/tokens.inline.css"), "utf8");
const demo = readFileSync(join(ROOT, "design/system/demo-data.v3.json"), "utf8");

const outputs = {
  "engine/src/cli/design-tokens.ts": tokensTs,
  "engine/src/output/inline-css.ts":
    "// GENERATED by engine/scripts/sync-design.mjs from design/system/generated/tokens.inline.css. Do not edit by hand.\n"
    + "// The single-file HTML report's stylesheet: the design tokens plus the six subset OFL faces as data: URLs.\n"
    + `export const INLINE_CSS: string = ${JSON.stringify(css)};\n`,
  "engine/src/demo/data.ts":
    "// GENERATED by engine/scripts/sync-design.mjs from design/system/demo-data.v3.json. Do not edit by hand.\n"
    + "// ANALYTIC demo data (synthetic, deterministic). `wasitme demo` turns it into engine output; it is never mixed with real data.\n"
    + `export const DEMO_JSON: string = ${JSON.stringify(demo)};\n`,
};

let bad = 0;
for (const [rel, text] of Object.entries(outputs)) {
  const path = join(ROOT, rel);
  const same = existsSync(path) && readFileSync(path, "utf8") === text;
  if (check) {
    if (!same) { console.error(`out of date: ${rel}`); bad++; }
  } else if (!same) {
    writeFileSync(path, text);
    console.log(`wrote ${rel}`);
  }
}
if (check) process.exit(bad === 0 ? 0 : 1);
