/**
 * Pure classifiers for Claude Code JSONL records. Text passed through here is inspected in memory
 * only; nothing returned is ever stored except lengths, booleans and allow-listed labels.
 */
import { obj } from "../../util.js";
import { effortLabel, isKnownLabel } from "./labels.js";

export type Rec = Record<string, unknown>;

/** User-record text Claude Code writes when the user presses Esc (also "… for tool use]"). */
export const INTERRUPT_PREFIX = "[Request interrupted by user";
/** Tool-result text written when the user rejects a permission prompt (pre-`toolDenialKind` logs). */
export const REJECT_PREFIX = "The user doesn't want to proceed with this tool use";
/** Tool-result text written when the user interrupts while a tool is running. */
export const CANCEL_PREFIX = "The user doesn't want to take this action right now";
/** Synthetic assistant error text for a request the user aborted. */
export const ABORTED_PREFIX = "API Error: Request was aborted";

/** Tools that look at the codebase without changing it. */
export const READ_TOOLS: ReadonlySet<string> = new Set(["Read", "Grep", "Glob", "LS", "NotebookRead"]);
/** Tools that change files. */
export const EDIT_TOOLS: ReadonlySet<string> = new Set(["Edit", "Write", "MultiEdit", "NotebookEdit"]);
/**
 * Tools that run a shell command. Their failures are the `toolErrorsCmd` side of the split (METHOD.md §3): mostly
 * non-zero exits, which reflect the code under test. Every other tool's failure is `toolErrorsEdit`.
 */
export const COMMAND_TOOLS: ReadonlySet<string> = new Set(["Bash", "PowerShell"]);
/** Error text Claude Code writes when it refuses a tool call before running it (invalid input, unknown tool). */
export const TOOL_USE_ERROR_PREFIX = "<tool_use_error>";
/** First line of a failed command's result ("Exit code 1"). Only used when the tool_use itself was never seen. */
const EXIT_CODE = /^Exit code -?\d+/;
/** Tools whose use makes a specific file's content known to the agent. */
const KNOWING_TOOLS: ReadonlySet<string> = new Set(["Read", "NotebookRead", "Write"]);
/** Tools that modify part of an existing file (blind-edit candidates). `Write` replaces whole files. */
const MODIFYING_TOOLS: ReadonlySet<string> = new Set(["Edit", "MultiEdit", "NotebookEdit"]);

/** Text injected by Claude Code into user records that is not something the human typed. */
const INJECTED: readonly RegExp[] = [
  /^</, // <command-name>, <local-command-stdout>, <local-command-caveat>, <task-notification>, <system-reminder>, IDE tags
  /^\[Request interrupted/,
  /^\[Your previous response/,
  /^This session is being continued from a previous conversation/,
  /^Stop hook feedback:/,
  /^Caveat: The messages below were generated by the user while running local commands/,
];

export function str(v: unknown): string | undefined {
  return typeof v === "string" ? v : undefined;
}

export function blocks(content: unknown): Rec[] {
  if (!Array.isArray(content)) return [];
  const out: Rec[] = [];
  for (const b of content) {
    const o = obj(b);
    if (o) out.push(o);
  }
  return out;
}

/** Text of a message/tool-result content: the string itself, or its `text` blocks. */
export function textParts(content: unknown): string[] {
  if (typeof content === "string") return [content];
  const out: string[] = [];
  for (const b of blocks(content)) if (b.type === "text" && typeof b.text === "string") out.push(b.text);
  return out;
}

export function isInterruptText(parts: readonly string[]): boolean {
  return parts.some((p) => p.trimStart().startsWith(INTERRUPT_PREFIX));
}

function isInjected(text: string): boolean {
  return INJECTED.some((re) => re.test(text));
}

/**
 * If this user record is a real human prompt, returns what the human typed ("" for an image-only
 * prompt); otherwise undefined. Modern logs mark prompts with `origin.kind == "human"`; for logs
 * that predate `origin`, a conservative filter (research #7) drops meta/compaction/tool-result
 * carriers and Claude-injected text. Prompts that start with "[Image #1]" are kept.
 */
export function humanPromptText(d: Rec): string | undefined {
  if (d.isSidechain === true) return undefined;
  const content = obj(d.message)?.content;
  const parts = textParts(content);
  if (isInterruptText(parts)) return undefined;
  const origin = obj(d.origin);
  if (origin) return origin.kind === "human" ? parts.join("\n").trim() : undefined;
  if (d.isMeta === true || d.isCompactSummary === true || d.toolUseResult !== undefined) return undefined;
  const bs = blocks(content);
  if (bs.some((b) => b.type === "tool_result")) return undefined;
  const human = parts.map((p) => p.trim()).filter((p) => p && !isInjected(p));
  if (human.length) return human.join("\n");
  if (!parts.some((p) => p.trim()) && bs.some((b) => b.type === "image")) return "";
  return undefined;
}

/** True for a user record that records an Esc interrupt (string or block form). */
export function isInterruptRecord(d: Rec): boolean {
  return isInterruptText(textParts(obj(d.message)?.content));
}

/**
 * Text of a prompt the human typed while the agent was working (`queued_command` attachment), or
 * undefined for task notifications, peer messages, meta and sidechain records.
 */
export function queuedHumanText(d: Rec, a: Rec): string | undefined {
  if (a.type !== "queued_command" || d.isMeta === true || d.isSidechain === true) return undefined;
  const origin = obj(a.origin) ?? obj(d.origin);
  if (origin) {
    if (origin.kind !== "human") return undefined;
  } else if (a.commandMode !== undefined && a.commandMode !== "prompt") {
    return undefined;
  }
  return textParts(a.prompt).join("\n").trim();
}

/** A legacy `queue-operation` remove that delivered a typed prompt mid-turn: its text, else undefined. */
export function queueRemoveText(d: Rec): string | undefined {
  if (d.operation !== "remove") return undefined;
  if (d.reason !== undefined && d.reason !== "absorbed_mid_turn") return undefined;
  const text = str(d.content)?.trim();
  if (!text || text.startsWith("<")) return undefined;
  return text;
}

export type ResultKind = "ok" | "error" | "rejected" | "blocked" | "interrupt";

/** Which side of the tool-error split a failed tool result counts on. */
export type ErrorSide = "cmd" | "edit";

/**
 * Split one failed tool result (METHOD.md §3): a command tool's failure is `cmd` unless Claude Code refused the call
 * before running it (a `<tool_use_error>`, e.g. invalid input), which is the agent's own tool-use failure (`edit`).
 * Every other tool is `edit` (edit/apply, MCP, web, subagent and other non-command failures). `isCommand` is
 * undefined when the tool_use was never seen; then the result text decides ("Exit code N" → `cmd`).
 */
export function errorSide(b: Rec, isCommand: boolean | undefined): ErrorSide {
  const text = textParts(b.content).join("\n").trimStart();
  if (isCommand === undefined) return EXIT_CODE.test(text) ? "cmd" : "edit";
  if (!isCommand) return "edit";
  return text.startsWith(TOOL_USE_ERROR_PREFIX) ? "edit" : "cmd";
}

/**
 * Classify one tool_result block. `toolDenialKind` (modern logs) wins: user rejections are
 * "rejected", every other denial (auto-mode classifier, permission rules) is "blocked". Neither is a
 * tool failure. A cancelled-by-interrupt result is an interrupt, not an error.
 */
export function toolResultKind(d: Rec, b: Rec): ResultKind {
  const denial = d.toolDenialKind;
  if (typeof denial === "string") return denial.startsWith("user") ? "rejected" : "blocked";
  if (b.is_error !== true) return "ok";
  const text = textParts(b.content).join("\n").trimStart();
  if (text.startsWith(CANCEL_PREFIX) || text.startsWith(INTERRUPT_PREFIX)) return "interrupt";
  if (text.startsWith(REJECT_PREFIX)) return "rejected";
  return "error";
}

const COMMAND = /<command-name>\/?(model|effort)<\/command-name>/;

/**
 * A `/model` or `/effort` local command recorded as a user record or a system local_command.
 * Only Claude-injected command text (starting with a tag) qualifies; older versions put
 * `<command-message>` before `<command-name>`, so the tag may appear anywhere in it.
 */
export function localCommand(d: Rec): "model" | "effort" | undefined {
  let text: string | undefined;
  if (d.type === "user") text = textParts(obj(d.message)?.content).join("\n");
  else if (d.type === "system" && d.subtype === "local_command") text = str(d.content);
  text = text?.trimStart();
  if (!text?.startsWith("<")) return undefined;
  const m = COMMAND.exec(text);
  return m ? (m[1] as "model" | "effort") : undefined;
}

/** Effort label on an assistant record (`effort`, else a string `perTurnEffort`; "other" only if neither fits). */
export function effortOf(d: Rec): string | undefined {
  const e = effortLabel(d.effort);
  if (isKnownLabel(e)) return e;
  const p = typeof d.perTurnEffort === "string" ? effortLabel(d.perTurnEffort) : undefined;
  return isKnownLabel(p) ? p : e ?? p;
}

export interface ToolUse {
  id: string | undefined;
  name: string;
  /** File the tool targets (in memory only; never stored or exported). */
  path: string | undefined;
  isRead: boolean;
  isEdit: boolean;
  /** Makes the target file's full content known (Read/NotebookRead/Write). */
  knows: boolean;
  /** Partial modification of an existing file (Edit/MultiEdit/NotebookEdit). */
  modifies: boolean;
  /** Runs a shell command (Bash/PowerShell). */
  isCommand: boolean;
}

export function toolUse(b: Rec): ToolUse {
  const name = str(b.name) ?? "";
  const input = obj(b.input);
  const path = str(input?.file_path) ?? str(input?.notebook_path);
  return {
    id: str(b.id),
    name,
    path: path || undefined,
    isRead: READ_TOOLS.has(name),
    isEdit: EDIT_TOOLS.has(name),
    knows: KNOWING_TOOLS.has(name),
    modifies: MODIFYING_TOOLS.has(name),
    isCommand: COMMAND_TOOLS.has(name),
  };
}

/**
 * Merge key for one model response. Claude Code writes each content block of a streamed response
 * as its own line repeating `usage`; lines share `message.id` + `requestId`. Without a requestId
 * (gateways/relays may reuse message ids across requests), the input-side usage disambiguates:
 * lines of one response repeat it, different requests almost never share it exactly.
 */
export function stepKey(d: Rec, msg: Rec): string {
  const req = str(d.requestId);
  const id = str(msg.id);
  if (req) return `r:${req}|${id ?? ""}`;
  const u = obj(msg.usage);
  if (id && u) return `m:${id}|${String(u.input_tokens)}|${String(u.cache_read_input_tokens)}|${String(u.cache_creation_input_tokens)}`;
  return `t:${id ?? ""}|${str(d.timestamp) ?? str(d.uuid) ?? ""}`;
}
