/**
 * Named scenarios: small config objects over one engine. Event days are fractions of the run length
 * so `--days` rescales a scenario without moving the planted change off the end.
 *
 * "Effects" are multiplicative factors on base rates (see params.ts). A scenario that must stay
 * flagged-free has none; its CLI version bumps (every ~3 days, generated by the schedule) carry no
 * factors, which is the null hypothesis the product must not flag.
 */
import { DEFAULT_NOISE, defaultInitial, makeParams, type ScheduleEvent, type SynthParams } from "./params.js";

export interface ScenarioOptions { seed?: number; days?: number; scale?: number }

export interface Scenario {
  name: string;
  description: string;
  defaultSeed: number;
  /** Default length in days. */
  defaultDays: number;
  build(opts: ScenarioOptions): SynthParams;
}

function make(
  base: { name: string; description: string; seed: number; days: number },
  cfg: (days: number, at: (frac: number) => number) => Partial<SynthParams> & { events?: ScheduleEvent[] },
): Scenario {
  return {
    name: base.name,
    description: base.description,
    defaultSeed: base.seed,
    defaultDays: base.days,
    build(opts) {
      const days = opts.days ?? base.days;
      const at = (frac: number): number => Math.min(days - 1, Math.max(1, Math.round(days * frac)));
      const over = cfg(days, at);
      const scale = opts.scale ?? 1;
      const volume = over.exchangesPerDay ?? { "claude-code": 15, codex: 12 };
      return makeParams({
        ...over,
        seed: opts.seed ?? base.seed,
        days,
        exchangesPerDay: { "claude-code": volume["claude-code"] * scale, codex: volume.codex * scale },
      });
    },
  };
}

const ev = (e: ScheduleEvent): ScheduleEvent => e;

export const SCENARIOS: Scenario[] = [
  make(
    { name: "null-few-long", description: "Few very long sessions; version bumps every ~3 days with NO effect. Nothing may be flagged.", seed: 101, days: 56 },
    () => ({ agents: ["claude-code"], shape: "few-long", exchangesPerDay: { "claude-code": 14, codex: 12 } }),
  ),
  make(
    { name: "null-many-short", description: "Many short sessions; version bumps every ~3 days with NO effect. Nothing may be flagged.", seed: 102, days: 56 },
    () => ({ agents: ["claude-code"], shape: "many-short", exchangesPerDay: { "claude-code": 16, codex: 12 } }),
  ),
  make(
    { name: "effort-drop-you", description: "You lower effort high->medium (a /effort command is in the log) and thinking depth falls, blind edits and pushback rise.", seed: 103, days: 56 },
    (_d, at) => ({
      agents: ["claude-code"], shape: "many-short", exchangesPerDay: { "claude-code": 16, codex: 12 },
      events: [ev({
        day: at(0.5), agent: "claude-code", kind: "effort", to: "medium", by: "you",
        effect: { thinkDepth: 0.45, blindEdit: 2.5, pushback: 3 },
        note: "user lowered effort",
      })],
    }),
  ),
  make(
    { name: "version-regression-agent", description: "A CLI version bump (no user action) multiplies tool errors (x2.5), interrupts and blind edits (x3). The vendor changed, not you.", seed: 104, days: 56 },
    (_d, at) => ({
      agents: ["claude-code"], shape: "few-long", exchangesPerDay: { "claude-code": 15, codex: 12 },
      events: [ev({
        day: at(0.55), agent: "claude-code", kind: "version", to: "next", by: "agent",
        effect: { toolError: 2.5, interrupt: 3, blindEdit: 3 },
        note: "regression shipped in this version",
      })],
    }),
  ),
  make(
    { name: "confounded-same-week", description: "Model change, effort change, config edit and a version bump all land in one week, each with effects. Cause unclear.", seed: 105, days: 56 },
    (_d, at) => {
      const d = at(0.5);
      return {
        agents: ["claude-code"], shape: "many-short", exchangesPerDay: { "claude-code": 16, codex: 12 },
        events: [
          ev({ day: d, agent: "claude-code", kind: "model", to: "claude-sonnet-5-5", by: "you", effect: { toolError: 1.5, thinkDepth: 0.7 } }),
          ev({ day: d + 1, agent: "claude-code", kind: "instructions", to: "next", by: "you" }),
          ev({ day: d + 2, agent: "claude-code", kind: "effort", to: "medium", by: "you", effect: { blindEdit: 1.8, pushback: 1.5 } }),
          ev({ day: d + 3, agent: "claude-code", kind: "version", to: "next", by: "agent", effect: { interrupt: 1.7 } }),
        ],
      };
    },
  ),
  make(
    { name: "insufficient-new-user", description: "A brand-new user: six days, a handful of exchanges, a version bump and a model change with no planted effect.", seed: 106, days: 6 },
    (_d, at) => ({
      agents: ["claude-code"], shape: "many-short", exchangesPerDay: { "claude-code": 3, codex: 3 },
      versionBumpEveryDays: 3,
      events: [ev({ day: at(0.7), agent: "claude-code", kind: "model", to: "claude-sonnet-5-5", by: "you" })],
    }),
  ),
  make(
    { name: "codex-only", description: "Codex only: you raise effort medium->high at mid-run and output tokens per step and tool calls per exchange rise.", seed: 107, days: 56 },
    (_d, at) => ({
      agents: ["codex"], shape: "many-short", exchangesPerDay: { "claude-code": 15, codex: 14 },
      events: [ev({
        day: at(0.5), agent: "codex", kind: "effort", to: "high", by: "you",
        effect: { outTok: 1.8, toolCalls: 1.5 },
        note: "user raised effort",
      })],
    }),
  ),
  make(
    { name: "both-agents", description: "Both agents: Claude effort drop by you, Codex version regression by the vendor - independent, in different weeks.", seed: 108, days: 56 },
    (_d, at) => ({
      agents: ["claude-code", "codex"], shape: "many-short", exchangesPerDay: { "claude-code": 14, codex: 14 },
      events: [
        ev({ day: at(0.45), agent: "claude-code", kind: "effort", to: "medium", by: "you", effect: { thinkDepth: 0.45, blindEdit: 2.5, pushback: 3 } }),
        ev({ day: at(0.65), agent: "codex", kind: "version", to: "next", by: "agent", effect: { toolError: 2.5, interrupt: 3 } }),
      ],
    }),
  ),
  // Not one of the eight: a small, edge-case-dense corpus meant to be committed as a seed fixture.
  make(
    { name: "tiny-both", description: "Fixture: a week of both agents with elevated edge-case rates (resume, fork, legacy, subagents, compaction, interrupts, era change).", seed: 109, days: 7 },
    (_d, at) => ({
      agents: ["claude-code", "codex"], shape: "many-short", exchangesPerDay: { "claude-code": 4, codex: 4 },
      initial: {
        ...defaultInitial("many-short"),
        "claude-code": { ...defaultInitial("many-short")["claude-code"], version: "2.1.246" },
      },
      rates: {
        ...makeParams({ seed: 0 }).rates,
        interrupt: 0.15, pushback: 0.2, queued: 0.4, apiRetry: 0.12, apiError: 0.02, compaction: 0.5, subagent: 0.25, toolCalls: 5,
        thinkDepth: 200,
      },
      noise: { ...DEFAULT_NOISE, resumeRate: 0.9, codexForkRate: 0.6, codexImportStubRate: 0.4, codexLegacyBelow: 144, notificationRate: 0.2, agentInitiatedRate: 0.3, codexExecPerDay: 1, clockGlitchRate: 0.05, codexOtherAbortRate: 0.05, codexArchiveRate: 0.5 },
      events: [
        ev({ day: at(0.5), agent: "claude-code", kind: "effort", to: "medium", by: "you", effect: { thinkDepth: 0.5 } }),
        ev({ day: at(0.6), agent: "codex", kind: "model", to: "gpt-6.1-sol", by: "you" }),
      ],
    }),
  ),
];

export function findScenario(name: string): Scenario | undefined {
  return SCENARIOS.find((s) => s.name === name);
}

export const NAMED_SCENARIOS = SCENARIOS.filter((s) => s.name !== "tiny-both").map((s) => s.name);
