#!/usr/bin/env node
// Embeds the shared contract goldens in fixtures.ts, and copies the design system's generated tokens into the mod.
// Zero dependencies.
//
//   node plugin/tests/fixtures/sync.mjs           regenerate fixtures.ts and plugin/mod/design-tokens.ts
//   node plugin/tests/fixtures/sync.mjs --check   fail if either is out of date
//
// plugin/mod/design-tokens.ts is design/system/generated/tokens.ts byte for byte (the engine keeps the same copy as
// engine/src/cli/design-tokens.ts): a mod can only import files inside its own plugin folder, so it cannot reach the
// design system's file directly.
//
// Why this exists: `claude plugin test` cannot import .json (a test only loads files named like
// code), so the exact text of each golden (contract/fixtures/{glance,tamper}/*.json) and of
// contract/fixtures/manifest.json is embedded in fixtures.ts. The goldens are shared with the engine
// and the Mac app, and are written by contract/fixtures/generate.mjs; this plugin keeps no private
// copies. Whether a golden validates against the schema is checked by the engine's contract tests.

import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const shared = join(here, '..', '..', '..', 'contract', 'fixtures')
const outPath = join(here, 'fixtures.ts')
const tokensSource = join(here, '..', '..', '..', 'design', 'system', 'generated', 'tokens.ts')
const tokensCopy = join(here, '..', '..', 'mod', 'design-tokens.ts')

const names = []
for (const dir of ['glance', 'tamper']) {
  for (const file of readdirSync(join(shared, dir)).filter(f => f.endsWith('.json')).sort()) {
    // Snapshot-shaped tamper files are for the Control Center, not the mod.
    if (dir === 'tamper' && !file.startsWith('glance-')) continue
    names.push(`${dir}/${file.slice(0, -'.json'.length)}`)
  }
}

const body = names
  .map(name => `  ${JSON.stringify(name)}: ${JSON.stringify(readFileSync(join(shared, `${name}.json`), 'utf8'))},`)
  .join('\n')
const manifest = readFileSync(join(shared, 'manifest.json'), 'utf8')
const generated = `// GENERATED by sync.mjs from contract/fixtures/. Do not edit; run:
//   node plugin/tests/fixtures/sync.mjs
// (\`claude plugin test\` cannot import .json, so the exact text of each shared golden is embedded here.)

export const FIXTURES = {
${body}
} as const

export type FixtureName = keyof typeof FIXTURES

/** contract/fixtures/manifest.json: what every consumer must decode from each golden. */
export const MANIFEST = ${JSON.stringify(manifest)}
`

const tokens = readFileSync(tokensSource, 'utf8')

function current(path) {
  try {
    return readFileSync(path, 'utf8')
  } catch {
    return '' // missing counts as out of date
  }
}

if (process.argv.includes('--check')) {
  let stale = false
  if (current(outPath) !== generated) {
    console.error('fixtures.ts is out of date: run node plugin/tests/fixtures/sync.mjs')
    stale = true
  }
  if (current(tokensCopy) !== tokens) {
    console.error('plugin/mod/design-tokens.ts differs from design/system/generated/tokens.ts: run node plugin/tests/fixtures/sync.mjs')
    stale = true
  }
  if (stale) process.exit(1)
  console.log(`fixtures ok: ${names.length} shared goldens + manifest; design tokens in sync`)
} else {
  writeFileSync(outPath, generated)
  writeFileSync(tokensCopy, tokens)
  console.log(`wrote fixtures.ts (${names.length} shared goldens + manifest) and mod/design-tokens.ts`)
}
